wget https://hbx.fhhrz.net/dl/fiXJWF4aHdkdofQuTxoNFj/SFingev2_01to04.zip
wget https://hbx.fhhrz.net/dl/fi77jSNPtkN9gG53c51PWM/SFingev2_05to08.zip
wget https://hbx.fhhrz.net/dl/fiLdgngPjAUUhuewuTPSqs/SFingev2_09to12.zip
wget https://hbx.fhhrz.net/dl/fiJ5SNJXqmtXP6rPooL9XU/SFingev2_13to16.zip
wget https://hbx.fhhrz.net/dl/fiVBvJwhL6QA6ffd3hbDZj/SFingev2_17to20.zip
wget https://hbx.fhhrz.net/dl/fiMCUseJWyC91wbx5mch3N/SFingev2_21to24.zip
wget https://hbx.fhhrz.net/dl/fiAJncQQsY5fcoNySe8Np3/SFingev2_25to28.zip
wget https://hbx.fhhrz.net/dl/fiNrAZXjCgUPyFJgfeTF7F/SFingev2_29to32.zip
wget https://hbx.fhhrz.net/dl/fiMh32qN9MmXZRZwvzVvpW/SFingev2_33to36.zip
wget https://hbx.fhhrz.net/dl/fiUUiBBqQbAdQCEK4p7BH5/SFingev2_37to40.zip
wget https://hbx.fhhrz.net/dl/fiQG2Xhogin67CA1f5PUaA/SFingev2_41to42.zip
wget https://hbx.fhhrz.net/dl/fiX4NzuNbBXVopwQLoTfY3/SFingev2_ValidationSameSubjects.zip
wget https://hbx.fhhrz.net/dl/fiEQ5AB3tv67X9wLnpQteV/SFingev2_ValidationSeparateSubjects.zip
wget https://hbx.fhhrz.net/dl/fi5TJNSdi8DVmSobE3LJt7/SFingev2Testsets.zip